# Generated by Django 2.2.2 on 2019-06-14 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='timestamp',
        ),
    ]
